### ISSUE TITLE
Parameters with default value are required by Phero

### ISSUE THREAD

**Issue by mael-queau** [phero-hq/phero#91] opened 2022-12-23 10:18 UTC
When using default values for function parameters, the resulting Phero Client requires the parameter to be given an explicit value even though it should be optional. Might be related to issue #90 .

![image](https://user-images.githubusercontent.com/100228262/209318329-f4d04df3-5938-4174-b5cf-8c66ee9522a9.png)

**Comment by Jpunt** [comment] 2022-12-23 10:42
Duplicate of #90

**Closed by Jpunt** 2022-12-23 10:42 UTC
Labels: duplicate
